[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "ws"
path = "src/bin/ws.rs"

[[bin]]
name = "cron"
path = "src/bin/cron/main.rs"

[dependencies]
lambda_runtime = "0.13"
lambda_http = "0.13"
tokio = { version = "1", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
sqlx = { version = "0.9", features = ["postgres", "runtime-tokio", "tls-rustls"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-openai = "0.27"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+1"] }
thiserror = "2"
typos = "0.10.43"
typos-vars = "0.10.4"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
scraper = { version = "0.22" }
async-trait = "0.1"
dotenvy = "0.15"
aws-sdk-s3 = "1.133.0"
aws-sdk-costexplorer = "1.123.0"
aws-sdk-ec2 = "1.242.0"
aws-sdk-sqs = "1.105.0"
anyhow = "1.0.104"

[dev-dependencies]
rstest = "0.23"
pretty_assertions = "1"
